FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
RUN npm ci

COPY server ./server
COPY database ./database
RUN npm run build -w server
RUN npm prune --omit=dev

FROM node:22-alpine AS production

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/server/package*.json ./server/
COPY --from=build /app/server/dist ./server/dist
COPY --from=build /app/database ./database

EXPOSE 3333

CMD ["npm", "run", "start", "-w", "server"]
